name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.17"
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: mix deps.get
      - run: mix playtest.install --with-deps
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
